Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2019-11, with the labels that each got.

#135 BLUEBUTTON-1361: Improve BFD Pipeline's async error handling
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/S3ToDatabaseLoadApp.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitor.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorWorker.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetTestUtilities.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/S3RifFile.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/TaskExecutor.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/task/DataSetMoveTask.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/task/S3TaskManager.java
  apps/bfd-pipeline/bfd-pipeline-rif-extract/src/test/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorWorkerIT.java
Labels: bug, enhancement

#134 BLUEBUTTON-1361: Fix pipeline data set move
  ops/terraform/modules/resources/bfd_pipeline/main.tf
Labels: bug

#141 BLUEBUTTON-1584: Allow JANUS to SSH into our instances
  ops/ansible/playbooks-ccs/vars/000_cross_env_vars.yml
Labels: enhancement

#139 BLUEBUTTON-1531: Add metrics and alarms for pipeline errors
  ops/terraform/modules/resources/bfd_pipeline/main.tf
  ops/terraform/modules/resources/bfd_pipeline/variables.tf
  ops/terraform/modules/stateless/main.tf
Labels: enhancement

#142 BLUEBUTTON-1584: Refactor ssh_users to support password auth for auditors
  ops/ansible/playbooks-ccs/roles/ssh_users/tasks/main.yml
  ops/ansible/playbooks-ccs/vars/000_cross_env_vars.yml
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/vault.yml
Labels: enhancement

#133 BLUEBUTTON-1379: Added support for running ITs against PostgreSQL
  apps/bfd-model/bfd-model-rif/pom.xml
  apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestHelper.java
  apps/bfd-model/bfd-model-rif/src/test/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManagerTest.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTestIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/S3ToDatabaseLoadAppIT.java
  apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/LoadAppOptions.java
  apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoader.java
  apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java
  apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTest.java
  apps/bfd-server/bfd-server-war/pom.xml
  apps/bfd-server/bfd-server-war/src/main/config/server-start.sh
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
  apps/dev/docker-compose.yml
  apps/pom.xml
  dev/devenv-readme.md
Labels: enhancement

#149 BLUEBUTTON-1376: Refactor metrics and alarms modules to be more granular and flexible
  ops/terraform/modules/resources/bfd_server_alarm/main.tf
  ops/terraform/modules/resources/bfd_server_alarm/variables.tf
  ops/terraform/modules/resources/bfd_server_metrics/main.tf
  ops/terraform/modules/resources/bfd_server_metrics/variables.tf
  ops/terraform/modules/stateless/main.tf
Labels: enhancement

#152 BLUEBUTTON-1376: Work around CloudWatch limitation
  ops/terraform/modules/resources/bfd_server_metrics/main.tf
Labels: bug
