Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2019-10, with the labels that each got.

#82 BLUEBUTTON-1288: Fix BFD Pipeline app's DB access
  ops/terraform/modules/resources/asg/main.tf
  ops/terraform/modules/resources/bfd_pipeline/main.tf
  ops/terraform/modules/resources/bfd_pipeline/variables.tf
  ops/terraform/modules/resources/ec2/main.tf
  ops/terraform/modules/resources/ec2/variables.tf
  ops/terraform/modules/stateless/main.tf
Labels: bug

#86 BLUEBUTTON-1288: Adding debug logging for Terraform locks
  ops/deploy-ccs.groovy
Labels: enhancement

#92 BLUEBUTTON-1288: Fixed the BFD Pipeline DB config
  ops/ansible/playbooks-ccs/build_bfd-pipeline.yml
  ops/ansible/playbooks-ccs/launch_bfd-pipeline.yml
  ops/ansible/playbooks-ccs/vars/prod/group_vars/all/vault.yml
  ops/ansible/playbooks-ccs/vars/test/group_vars/all/vault.yml
Labels: bug

#87 BLUEBUTTON-1288: Create BFD Pipeline EC2 instance after SGs
  ops/terraform/modules/resources/bfd_pipeline/main.tf
  ops/terraform/modules/resources/ec2/main.tf
  ops/terraform/modules/resources/ec2/variables.tf
Labels: bug

#84 BLUEBUTTON-1233: Enabling Hikari Logging
  apps/bfd-server/bfd-server-launcher/src/main/resources/logback.xml
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Labels: bug

#94 BLUEBUTTON-1288: Fixing Java formatting
  apps/bfd-server-test-perf/src/main/java/gov/cms/bfd/server/test/perf/utils/FhirClient.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Labels: bug

#93 BLUEBUTTON-1288: Revert accidental changes to DB migrations
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V11__Create_medicare_beneficiary_id_history_table.sql
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V13__Create_beneficiary_history_temp_table.sql
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V1__Create_beneficiary_and_claim_tables.sql
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V9__Create_beneficiary_history_table.sql
Labels: bug

#96 BLUEBUTTON-1288: BFD Pipeline S3 access
  ops/terraform/modules/resources/bfd_pipeline/main.tf
  ops/terraform/modules/resources/bfd_pipeline/variables.tf
  ops/terraform/modules/stateless/main.tf
Labels: bug, enhancement

#95 BLUEBUTTON-1288: CloudWatch log groups
  ops/ansible/playbooks-ccs/templates/cwagent-data-pipeline.json.j2
  ops/ansible/playbooks-ccs/templates/cwagent-data-server.json.j2
  ops/terraform/modules/stateful/main.tf
Labels: bug, enhancement

#97 BLUEBUTTON-1288: "Turbo Mode": Bump up RDS IOPS in PROD
  ops/terraform/env/prod/stateful/main.tf
Labels: enhancement

#98 BLUEBUTTON-1359: Enable deploys to the CCS prod environment
  Jenkinsfile
  ops/deploy-ccs.groovy
  ops/deploy-healthapt.groovy
Labels: enhancement

#99 BLUEBUTTON-1288: Allow EC2 instances to push to CloudWatch logs
  ops/terraform/modules/resources/iam/main.tf
Labels: bug

#100 BLUEBUTTON-1288: Fixed the bfd-pipeline/messages.txt log group name
  ops/ansible/playbooks-ccs/templates/cwagent-data-pipeline.json.j2
Labels: bug

#102 BLUEBUTTON-1288: Fix vault_data_pipeline_s3_bucket in prod-sbx
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/vault.yml
Labels: bug

#104 BLUEBUTTON-1359: Fix New Relic app name in CCS prod
  ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
Labels: bug

#109 BLUEBUTTON-1288: Bump space for RIF downloads to 1TB
  ops/terraform/modules/resources/bfd_pipeline/main.tf
Labels: bug
