Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2021-12, with the labels that each got.

#811 DCGEO-145: Claim based SAMHSA filtering with adapters
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/CodeableConcept.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/Coding.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/DiagnosisComponent.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/FhirResource.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/ItemComponent.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/ProcedureComponent.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/r4/ClaimAdapter.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/r4/ExplanationOfBenefitAdapter.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/stu3/ExplanationOfBenefitAdapter.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/AbstractSamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/AbstractR4SamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4EobSamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4SamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimSamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/SamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/Stu3EobSamhsaMatcher.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/AbstractSamhsaMatcherTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/AbstractR4SamhsaMatcherTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/SamhsaMatcherR4FromClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProviderTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimSamhsaMatcherTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/SamhsaMatcherFromClaimTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/SamhsaMatcherTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/Stu3EobSamhsaMatcherTest.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/metadata.json
  apps/bfd-server/bfd-server-war/src/test/resources/samhsa_codes_test_file.csv
Labels: dcgeo

#861 PACA-265: disabling hibernate schema validation for PACA-265
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Labels: paca

#879 PACA-265: adding pre-migrations needed for RDA API 0.5 changes
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V37__preadj_rda_0_5_table_updates.sql
Labels: paca

#880 PACA-265: adding a post migration for after the 0.5 RDA upgrade
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V38__preadj_rda_0_5_post_table_updates.sql
Labels: paca, db-migration

#881 PACA-265: enabling hibernate schema validation for PACA-265
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Labels: paca

#818 PACA-263: FHIR 0.1+ Claim transformer changes
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/BBCodingSystems.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/IdentifierType.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/AbstractTransformerV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimSamhsaMatcherTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimFissRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimMcsRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearch.json
Labels: paca
