Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2021-06, with the labels that each got.

#603 Kylerobbins/dcgeo 62 pre adj claim entities
  apps/bfd-model/bfd-model-rda/pom.xml
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissProcCode.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/package-info.java
  apps/bfd-model/pom.xml
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Labels: dcgeo

#564 DCGEO-42: Adding a NACL to control access to MPM VPC
  ops/terraform/env/prod-sbx/stateless/main.tf
  ops/terraform/env/prod-sbx/stateless/variables.tf
  ops/terraform/env/prod/stateless/main.tf
  ops/terraform/env/prod/stateless/variables.tf
  ops/terraform/env/test/stateless/main.tf
  ops/terraform/env/test/stateless/variables.tf
  ops/terraform/modules/resources/bfd_pipeline/main.tf
  ops/terraform/modules/resources/bfd_pipeline/variables.tf
  ops/terraform/modules/stateless/main.tf
  ops/terraform/modules/stateless/variables.tf
Labels: dcgeo

#649 BFD-897: Fix BFD Pipeline's init errors and job failure handling
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineManager.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTestIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/DatabaseOptions.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/databaseschema/DatabaseSchemaUpdateJob.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/jobs/store/PipelineJobRecordStore.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerIT.java
Labels: bug

#588 DCGEO-23: Integrate RDA FissClaims gRPC call pipeline
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/ConfigUtils.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/DcGeoRdaLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/PreAdjudicatedClaim.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/ProcessingException.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/SkeletonRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/SkeletonRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCaller.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcResponseStream.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcStreamCaller.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_claim.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_claim_status.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_diagnosis_code.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_diagnosis_present_on_admission_indicator.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_procedure_code.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/fiss/fiss_processing_type.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_beneficiary_sex.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_billing_provider_indicator.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_billing_provider_status_code.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_claim.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_claim_type.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_detail.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_detail_status.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_diagnosis_code.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/mcs/mcs_diagnosis_icd_type.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/proto/rda/v1/rda.proto
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/DcGeoRdaLoadJobTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/ProcessingExceptionTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadJobTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptionsTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcResponseStreamTest.java
  apps/bfd-pipeline/pom.xml
Labels: dcgeo, enhancement

#612 DCGEO-59: pre-adj claim transformers
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissProcCode.java
  apps/bfd-server/bfd-server-war/pom.xml
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimResponseTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResponseResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDao.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ResourceTransformer.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ResourceTypeV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProviderTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResourceProviderTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResponseResourceProviderTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDaoTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/AssertUtils.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/ReflectionTestUtils.java
  apps/bfd-server/pom.xml
Labels: dcgeo

#661 BFD-897: Get Full Stack Traces from Surefire and Failsafe
  apps/pom.xml
Labels: enhancement

#663 BFD-897: Fix and diagnose unstable Jenkins builds
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineManager.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineManagerIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/resources/logback-test.xml
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/jobs/store/PipelineJobRecordStore.java
Labels: bug

#665 BFD-897: Remove 000_cross_env_vars.yml symlink loop
  ops/ansible/playbooks-ccs/host_vars/builds.bfd-mgmt.cmscloud.local/000_cross_env_vars.yml
Labels: bug

#668 BFD-826: Add tracing to Patient search by Part D contract
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Labels: enhancement

#673 BFD-826: Remove unneeded join to bene monthly table
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Labels: bug

#664 BFD-897: Redirect all test output to separate files
  .github/workflows/ci-java.yml
  apps/bfd-model/bfd-model-codebook-extractor/pom.xml
  apps/bfd-model/pom.xml
  apps/bfd-pipeline/bfd-pipeline-app/pom.xml
  apps/bfd-pipeline/bfd-pipeline-benchmarks/pom.xml
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
  apps/bfd-pipeline/bfd-pipeline-shared-utils/pom.xml
  apps/bfd-pipeline/pom.xml
  apps/bfd-server-test-perf/pom.xml
  apps/bfd-server/bfd-server-launcher/pom.xml
  apps/bfd-server/bfd-server-war/pom.xml
  apps/pom.xml
Labels: enhancement

#659 DCGEO-26: Adds FissClaimsRdaSink to write RDA FISS claims in database
  apps/bfd-model/bfd-model-rda/pom.xml
  apps/bfd-model/bfd-model-rda/src/main/resources/META-INF/persistence.xml
  apps/bfd-model/bfd-model-rda/src/test/java/gov/cms/bfd/model/rda/SchemaMigrationIT.java
  apps/bfd-pipeline/bfd-pipeline-app/pom.xml
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTestIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/FissClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCaller.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcResponseStream.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptionsTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/pom.xml
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/DatabaseUtils.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/IdHasher.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/test/java/gov/cms/bfd/pipeline/sharedutils/IdHasherTest.java
  apps/bfd-server-test-functions/pom.xml
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerIT.java
Labels: dcgeo, enhancement
