Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2021-07, with the labels that each got.

#681 BFD-1024: Refactor and cache test utils
  apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestUtils.java
  apps/bfd-model/bfd-model-rif/src/test/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManagerTest.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/MetricOptions.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineManagerIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/pom.xml
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/ExtractionOptions.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/CcwRifLoadTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadJobIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/ManifestEntryDownloadTaskIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/FissClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/pom.xml
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/DatabaseOptions.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/DatabaseUtils.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineTestUtils.java
  apps/bfd-pipeline/pom.xml
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/AuthenticationIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/MetricsAdminServletIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerCapabilityStatementIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/BeneficiaryTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorV2IT.java
Labels: enhancement

#685 BFD-1057: Add pre-flight check to Patient search by Part D
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Labels: bug

#690 BFD-1065: Simplify Part D contract-year-month count DB query
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Labels: bug

#644 DCGEO-66: search Claim/ClaimResponse by MBI
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/QueryUtils.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimResponseTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResponseResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDao.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ResourceTypeV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProviderTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDaoTest.java
Labels: dcgeo

#667 DCGEO-65: Add feature flag implementation
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
  contributing/docker/Dockerfile
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml
  ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
  ops/ansible/playbooks-ccs/vars/test/group_vars/all/env_specific.yml
  ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
Labels: dcgeo

#707 adding a pre-commit hook to check for decrypted secrets
  .gitignore
  .secrets
  README.md
  apps/pom.xml
Labels: security

#617 [BFD-880] - GitHub Actions use latest stable Java 8 for builds.
  .github/workflows/ci-java.yml
Labels: CI/CD

#691 DCGEO-123: RDA API Pipeline setup for TEST environment
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/DirectRdaLoadApp.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/AbstractRdaLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaFissClaimLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaMcsClaimLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGenerator.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCaller.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimStreamCaller.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/AbstractRdaLoadJobTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
  ops/ansible/playbooks-ccs/vars/test/group_vars/all/env_specific.yml
  ops/ansible/playbooks-ccs/vars/test/group_vars/all/vault.yml
  ops/ansible/roles/bfd-pipeline/README.md
  ops/ansible/roles/bfd-pipeline/defaults/main.yml
  ops/ansible/roles/bfd-pipeline/templates/bluebutton-data-pipeline.sh.j2
Labels: dcgeo

#718 [BFD-1126] Fix pipeline app failing when a schema migration is needed
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/DirectRdaLoadApp.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/JpaClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineTestUtils.java
Labels: dcgeo

#694 BFD-1071: Created DB Query Checker utility
  .github/workflows/ci-rust.yml
  apps/utils/db-query-checker/.cargo/config
  apps/utils/db-query-checker/Cargo.lock
  apps/utils/db-query-checker/Cargo.toml
  apps/utils/db-query-checker/README.md
  apps/utils/db-query-checker/env.sample
  apps/utils/db-query-checker/results/.gitignore
  apps/utils/db-query-checker/results/db_query_checker_results_stats.md
  apps/utils/db-query-checker/src/csv_log.rs
  apps/utils/db-query-checker/src/db_queries/select_bene_count_by_part_d_contract_id_and_year_month.sql
  apps/utils/db-query-checker/src/db_queries/select_bene_ids_by_part_d_contract_id_and_year_month.sql
  apps/utils/db-query-checker/src/db_queries/select_bene_ids_by_part_d_contract_id_and_year_month_and_min_bene_id.sql
  apps/utils/db-query-checker/src/db_queries/select_bene_records_by_bene_ids.sql
  apps/utils/db-query-checker/src/db_queries/select_distinct_part_d_contract_ids.sql
  apps/utils/db-query-checker/src/db_queries/select_distinct_part_d_contract_ids_quicker.sql
  apps/utils/db-query-checker/src/lib.rs
  apps/utils/db-query-checker/src/main.rs
  apps/utils/db-query-checker/src/query.rs
Labels: enhancement
