Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2022-02, with the labels that each got.

#922 PACA-350: MBI caching 1/4 - create table
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V54__preadj_mbi_caching_create_table.sql
Labels: paca, db-migration

#923 PACA-350: MBI caching 2/4 - pipeline populates new table
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/Mbi.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjMcsClaim.java
  apps/bfd-model/bfd-model-rda/src/test/java/gov/cms/bfd/model/rda/SchemaMigrationIT.java
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V55__preadj_mbi_caching_populate_table.sql
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/RDABridgeIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGenerator.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimGenerator.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/MbiCache.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadJobIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaPipelineTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaServerJobIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGeneratorTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimSourceTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimGeneratorTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimSourceTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/MbiCacheIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCallerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimStreamCallerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/resources/FISS.ndjson
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/resources/MCS.ndjson
  apps/bfd-pipeline/bfd-pipeline-shared-utils/pom.xml
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/CachingIdHasher.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/IdHasher.java
Labels: paca, db-migration

#938 PACA-426: Allow empty strings in enum values
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/ClaimTransformerFieldTester.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
Labels: bug, paca

#924 PACA-350: MBI caching 3/4 - API queries new table
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjMcsClaim.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
  apps/bfd-server/bfd-server-war/pom.xml
  apps/bfd-server/bfd-server-war/src/main/config/server-start.sh
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimResponseTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDao.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ResourceTypeV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimResponseResourceProviderIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDaoIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDaoTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java
  apps/pom.xml
Labels: paca

#925 PACA-350: MBI caching 4/4 - drops obsolete mbi/hash columns
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V56__preadj_mbi_caching_drop_old_columns.sql
Labels: paca, db-migration

#942 PACA-390: Populate sandbox RDA data from S3
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/vault.yml
  ops/ansible/roles/bfd-pipeline/defaults/main.yml
  ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
Labels: paca

#954 PACA-452: Enables RDA API ETL pipeline in sandbox.
  ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml
Labels: paca

#930 PACA-371: Add feature to build attribution sql scripts
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/README.md
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/AppConfig.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/RDABridge.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/AbstractTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/FissTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/McsTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/util/AttributionBuilder.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/util/DataSampler.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/resources/example-config.yml
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/RDABridgeIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/attribution-template.json
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/expected/expected-attribution.json
  apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigLoader.java
  apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/ConfigLoaderTest.java
Labels: paca

#966 PACA-238: Migration only PR for PACA-238. Merge before PR 908.
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V57__rda_message_metadata.sql
Labels: paca, db-migration

#975 PACA-471: Add BatchSize annotations to pre-adj claim entities.
  apps/bfd-model/bfd-model-rda/pom.xml
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjMcsClaim.java
Labels: paca

#956 BFD-1473 - RFC: Separate Flyway from BFD Pipeline Application
  rfcs/0011-separate-flyway-from-pipeline.md
  rfcs/resources/0011-2022-02-deployment-sequence.plantuml
  rfcs/resources/0011-2022-02-deployment-sequence.svg
  rfcs/resources/0011-proposed-deployment-sequence.plantuml
  rfcs/resources/0011-proposed-deployment-sequence.svg
  rfcs/resources/README.md
Labels: RFC
