Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2022-04, with the labels that each got.

#794 DCGEO-219 (DRAFT): RFC for storing RDA claims using JSONB
  rfcs/0012-rda-claims-jsonb-DEFERRED.md
Labels: paca

#1040 PACA-529: No warning if token is blank/null
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceIT.java
Labels: paca

#1022 PACA-328: Adds schema migration file to produce new rda schema.
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V62__create_rda_schema.sql
Labels: paca, db-migration

#1023 PACA-486: convert code to use rda schema
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/Mbi.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaApiClaimMessageMetaData.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaApiProgress.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissAuditTrail.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissDiagnosisCode.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissPayer.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissProcCode.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsAdjustment.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsAudit.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsClaim.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsDetail.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsDiagnosisCode.java
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsLocation.java
  apps/bfd-model/bfd-model-rda/src/test/java/gov/cms/bfd/model/rda/SchemaMigrationIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaFissClaimLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaMcsClaimLoadJob.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadJobIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaServerJobIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCallerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimStreamCallerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineTestUtils.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/AbstractR4ResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimResponseTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/ClaimTypeV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/R4ClaimSamhsaMatcherTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/preadj/common/ClaimDaoIT.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java
Labels: paca

#1054 PACA-540: Fix date bug in FissClaimTransformer
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimFissRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimMcsRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearch.json
Labels: bug, paca

#1006 PACA-411: (BFD-1672) Add DCN to v2 EOB claims
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/BBCodingSystems.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/HHAClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/OutpatientClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/SNFClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/FissClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimResponseTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimFissRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimMcsRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimResponseFissRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimResponseMcsRead.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimResponseSearch.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearch.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadHha.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadHospice.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadInpatient.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadOutpatient.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadSnf.json
  apps/bfd-server/dev/api-changelog.md
Labels: paca

#1067 PACA-551: Fix claim status for MCS when null
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj/McsClaimTransformerV2.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearch.json
Labels: bug, paca

#1061 PACA-513: Use RIF Column enums to get column names.
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/FissTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/McsTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/BeneficiaryData.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/Fiss.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/Mcs.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/ModelUtil.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/model/FissTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/model/McsTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/model/ModelUtilTest.java
Labels: paca

#1071 PACA-555: Resolve illegal reflection warning from gRPC module
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
Labels: paca

#1062 PACA-510: drop obsolete pre_adj schema
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V64__drop_pre_adj_schema.sql
Labels: paca, db-migration

#1069 PACA-520: recognize rda api idle disconnects
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcResponseStream.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcResponseStreamTest.java
Labels: paca

#1089 udpating the rfc number for DSL RFC
  0014-dsl-driven-rda-code-generation.md
Labels: paca
