Repository CMSgov/beneficiary-fhir-data, pull requests merged in 2022-03, with the labels that each got.

#980 BFD-1566: Implement CCW RIF Filtering for 2022 Enrollment Issues
  apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/MappingSpec.java
  apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayoutsProcessor.java
  apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResource.java
  apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResourceGroup.java
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-1-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-1-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-2-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-2-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-3-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-3-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-3-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-4-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-4-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-4-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-5-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-6-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-6-pde-new-benes.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-6-pde.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-7-beneficiaries.txt
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-7-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-pde-4-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-pde-5-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-pde-6-manifest.xml
  apps/bfd-model/bfd-model-rif-samples/src/test/java/gov/cms/bfd/model/rif/samples/SampleDataColumnsTest.java
  apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/RifFileType.java
  apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/RifRecordEvent.java
  apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/SkippedRifRecord.java
  apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java
  apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/RifFilesProcessor.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/CcwRifLoadTestUtils.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/extract/RifFilesProcessorTest.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTest.java
  apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineTestUtils.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/BeneficiaryTransformerV2.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/BeneficiaryTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  apps/bfd-server/dev/api-changelog.md
  apps/utils/db-query-checker/src/db_queries/select_bene_records_by_bene_ids.sql
  ops/ansible/roles/bfd-pipeline/defaults/main.yml
  ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
Labels: enhancement

#992 BFD-1586: Fix Filtering Logic for Non-Bene Records
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
Labels: bug, enhancement

#998 BFD-1590: Fix Logging of Configuration at Pipeline Launch
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadOptions.java
  apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java
Labels: bug

#908 PACA-238: capture rda api meta data
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaApiClaimMessageMetaData.java
  apps/bfd-model/bfd-model-rda/src/test/java/gov/cms/bfd/model/rda/SchemaMigrationIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/AbstractClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkTest.java
Labels: paca

#996 PACA-480: Fix MCS ICD type logic
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/McsTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/carrier.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/expected/expected-mcs.ndjson
Labels: bug, paca

#1014 PACA-419: Add 4 new fields to FissClaims table - SQL Only PR
  apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V59__fiss_claims_prov_fields.sql
Labels: paca, db-migration

#941 PACA-432: Implement line item parsing for MCS claims
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/RDABridge.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/AbstractTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/FissTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/McsTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/Parser.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/etl/RifParser.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/io/NdJsonSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/io/RifSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/Fiss.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/model/Mcs.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/util/WrappedMessage.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/RDABridgeIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/etl/FissTransformerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/etl/McsTransformerIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/utils/TestUtils.java
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/carrier.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/expected/expected-fiss.ndjson
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/expected/expected-mcs.ndjson
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/home.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/hospice.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/inpatient.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/outpatient.csv
  apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/resources/snf.csv
Labels: paca

#1028 expanding the codeowners dirs owned by the PACA team
  .github/CODEOWNERS
Labels: paca

#971 PACA-419: Add 4 new fields to FissClaims table
  apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGenerator.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGeneratorTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
Labels: paca, db-migration

#866 BFD-1383: Update V2 line item allowed charge amount mapping
  apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2Test.java
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadCarrier.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadCarrierWithTaxNumbers.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadDme.json
  apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadDmeWithTaxNumbers.json
  apps/bfd-server/dev/api-changelog.md
Labels: pending-comms

#1026 PACA-425: reduce logging output and fix broken gauges
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/NumericGauges.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/AbstractClaimRdaSink.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSinkTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSinkTest.java
Labels: paca

#1021 PACA-321: Add JWT expiration notifications
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSourceIT.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/resources/logback-test.xml
  apps/pom.xml
Labels: paca

#1017 PACA-427: Add seq number to RDA tranform errors
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
  apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
Labels: paca
